name: "Sonar Scan"
description: "Run SonarQube scan"
runs:
  using: "composite"
  steps:
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6.0.0
      with:
        args: >
          -Dsonar.sources=src/main/java
          -Dsonar.java.binaries=target/classes
          -Dsonar.projectKey=${{ inputs.projectKey }}
          -Dsonar.organization=${{ inputs.organization }}
          -Dsonar.exclusions=**/DevopsApplication.java
      env:
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}