apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.keyname }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2h1Yi5kb2NrZXIuY29tL3JlcG9zaXRvcnkvZG9ja2VyL2JhaXNuYWtlL2Rldm9wcyI6eyJ1c2VybmFtZSI6ImJhaXNuYWtlIiwicGFzc3dvcmQiOiJDb3JlUGVyc2Vmb25hMjAwMSIsImVtYWlsIjoiY29yaW9sZXNlYTIwMDFAZ21haWwuY29tIiwiYXV0aCI6IlltRnBjMjVoYTJVNlEyOXlaVkJsY25ObFptOXVZVEl3TURFPSJ9fX0=
type: kubernetes.io/dockerconfigjson