apiVersion: v1
kind: Service
metadata:
  name: deployment-test-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}