name: "Run Sonar Scan"
description: "Run Sonar Scan through maven"
runs:
  using: "composite"
  steps:
    - name: SonarQube Scan
      shell: bash
      run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      with:
        args: >
          -Dsonar.token=${{ inputs.SONAR_TOKEN }}
          -Dsonar.sources=src/main/java
          -Dsonar.java.binaries=target/classes
          -Dsonar.projectKey=${{ inputs.projectKey }}
          -Dsonar.organization=${{ inputs.organization }}
          -Dsonar.exclusions=**/DevopsApplication.java