name: Maven Package

on: push

jobs:
  sonar_scan:
    uses: ./.github/workflows/sonar.yml
    with:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build_jar:
    needs: sonar_scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Create jar with maven
        run: mvn clean package --file pom.xml
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: devops-jar
          path: target/*.jar