name: Maven Package

on: push

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Create jar with maven
        run: mvn clean package --file pom.xml
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target/classes
  sonar_scan:
    needs: build_jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: target
          path: target/classes
      - uses: ./.github/actions/sonar
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          projectKey: CiobanuCorina_devops
          organization: ciobanucorina
