name: Maven Package

on: push

jobs:
  build_jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Create jar with maven
        run: mvn clean package --file pom.xml
      - name: Create target directory
        run: mkdir test
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: devops-jar
          path: test/*.jar