name: Maven Package

on: push

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Maven build
        run: mvn clean install --file pom.xml -Dmaven.test.skip=true
      - name: Run tests
        run: mvn verify --file pom.xml
      - name: Upload target
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target
  sonar_scan:
    needs: build_jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: target
          path: target
      - uses: ./.github/actions/sonar-maven
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          projectKey: CiobanuCorina_devops
          organization: ciobanucorina
  docker_build:
    needs: sonar_scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: target
          path: target
      - name: Build Docker image
        uses: ./.github/actions/docker
        with:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}