name: SonarQube Scan

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: .
      - name: Show downloaded files (debug)
        run: |
            echo "Listing repo root:"
            ls -la
            echo "Listing target:"
            ls -la target || true
            echo "Listing target/classes:"
            ls -la target/classes || true
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sources=src/main/java
            -Dsonar.java.binaries=target/classes